### ISSUE TITLE
calculate areas in m2

### ISSUE THREAD

**Issue by mpadge** [moveability/moveability#10]
Convex hulls around points are in lon-lat, but these could be used to do very quick and hopefully only mildly inaccurate areal calculations with the `clipper` routines. The principle:
``` r
d <- geodist::geodist (hull) # hull is one hull
xy <- data.frame (cmdscale (d))
names (xy) <- c ("x", "y")
```
and then submit that to the clipper routine

**Comment by mpadge** [comment]
[This commit](https://github.com/moveability/moveability/commit/02f038ca4c6860997dea2dd43b0c711ade3f5917) adds an `rcpp_area` function that allows this functionality (code is mostly just the structure of `move_stats()`):

``` r
devtools::load_all (".", export_all = TRUE)
#> Loading moveability
streetnet <- castlemaine
quiet <- FALSE
mode <- "foot"
obj <- construct_moveability_objects (streetnet, mode, quiet)
#> contracting street network ...
#> Loading required namespace: geodist
#> done in 1 seconds.
graph <- obj$net
from <- obj$from
d_threshold <- 700

v <- dodgr::dodgr_vertices (graph) # used to extract points below
vert_map <- make_vert_map (graph)
from_index <- match (from, vert_map$vert) - 1 # 0-based
vert_id <- vert_map$vert [from_index + 1]
graph <- convert_graph (graph)

d <- rcpp_get_sp_dists_par (graph, vert_map, from_index, d_threshold,
                            heap_type = "BHeap")
d <- matrix (d, nrow = nrow (vert_map), ncol = length (from_index))

dmat <- d
vertices <- v
pts <- apply (dmat, 2, function (i) which (i > 0))
names (pts) <- vert_id

hulls <- get_hulls (dmat, v, vert_id, vert_map)
index <- vapply (hulls, function (i) nrow (i) > 3, logical (1))
hulls <- hulls [index]

areas_clipper <- function (hulls) {
    xy <- lapply (hulls, function (i) {
                      if (nrow (i) < 3)
                          return (0)
                      d <- geodist::geodist (i)
                      xy <- data.frame (cmdscale (d))
                      names (xy) <- c ("x", "y")
                      return (xy)   })
    rcpp_areas (xy)
}

areas_sf <- function (hulls) {
    xy <- lapply (hulls, function (i)
                  sf::st_polygon (list (as.matrix (i [, c ("x", "y")]))) %>%
                        sf::st_sfc (crs = 4326))
    xy <- do.call (c, xy)
    as.numeric (sf::st_area (xy))
}

rbenchmark::benchmark (
                       areas_clipper (hulls),
                       areas_sf (hulls),
                       replications = 10)
#> Linking to GEOS 3.7.1, GDAL 2.4.1, PROJ 5.2.0
#>                   test replications elapsed relative user.self sys.self
#> 1 areas_clipper(hulls)           10   3.037    1.000     3.031        0
#> 2      areas_sf(hulls)           10   4.818    1.586     4.806        0
#>   user.child sys.child
#> 1          0         0
#> 2          0         0
```

<sup>Created on 2019-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And `clipper` is just over 50% faster, which is not a heap, but the important thing is that the C++ function can be called directly as part of other C++ routines which will make it possible to easily incorporate areal calculations in m<sup>2</sup> within other C++ routines.

---

@mdsumner don't worry about any of the details here, but this is me working out the kinds of routines I can easily extract from the clipper library. Note that this has already been wrapped by Adrian Badderly as [`polyclip`](https://github.com/baddstats/polyclip), so no real point repeating that, ... *but* ... what I've been doing here has been vectorizing all operations, which `polyclip` does not do. I'll likely just open some issues over there.

**Comment by mdsumner** [comment]
Very nice, been hoping to have a closer look some time!  BTW, do you also know a general line segment discretization tool? I want a grid, and line segments with value - the proportion of the length of line segment within a cell dictates the value aded to the cell by the segment. Can use it for a very literal "time spent" summary, which might be of interest here?

**Comment by mpadge** [comment]
Nope, I do not. That's yet another instance that needs under the hood a turbo-charged point-in-poly routine, which I [have not yet got around to](https://github.com/hypertidy/kern) because `clipper` does that, so I've been using that. If I had to do that, I'd build it with `clipper`, and use the internal `IntersectEdges` method of the `clipper` class to get the points. Short of that, I'm no help, sorry. But yeah, you're definitely right that it would/could be of interest, so the general problem is definitely being filed in my "maybe-get-back-to-this" box ...

**Comment by mdsumner** [comment]
Oh cool, that's helpful to know

**Comment by mpadge** [comment]
~~Nah, actually scrap that - clipper's `IntersectEdges` routine is really hard-coded for polygon intersections, and comes with a mass of overhead that is no way going to make it flexible enough here. I reckon this should be pretty easy to crack just using clipper's `PointInPolygon` and going from there. I shall report back ...~~

Edit: Scrap that comment, because clipper intersects polygons and lines just as easily, and has been [implemented here](https://github.com/moveability/moveability/commit/61003317a5fc75bb92254aaa08b20db79074381b)
