### ISSUE TITLE
Aggregate point-based measures to polygons

### ISSUE THREAD

**Issue by mpadge** [moveability/moveability#3]
The point-based calculations are not a good way to visually present results, and all other walkability systems use polygons (census blocks, whatever) which look much better. Maybe try polygonizing the street network?

**Comment by Robinlovelace** [comment]
This raises an interesting question: how to break-up a street network, given only the streets?

**Comment by mpadge** [comment]
Yeah, @mdsumner and I have discussed that. Can't remember where at the moment, but somewhere in the context of [`decido`](https://github.com/hypertidy/decido). There are routines for finding shortest cycles in a graph (liked used in [`osmplotr` here](https://github.com/ropensci/osmplotr/blob/master/R/get-highway-cycle.R)). This should just be a matter of applying [`ggm::fundCycles()`](https://cran.r-project.org/web/packages/ggm/index.html), but I don't know how well that scales ... Otherwise should be reasonably trivial to implement an optimised C++ version (likely in `dodgr`).

Edit: `ggm` definitely will not scale - it's all pure R code with loads of `for` loops, with last update in 2015. Good pseudo-code [here](https://www.codeproject.com/Articles/1158232/%2fArticles%2f1158232%2fEnumerating-All-Cycles-in-an-Undirected-Graph) and [this SO Q](https://stackoverflow.com/questions/16782898/algorithm-for-finding-minimal-cycles-in-a-graph). @mdsumner any insights please into how useful it would/might be to have a general function to find fundamental cycles in a graph? Worthy of putting in `dodgr`? Note that I am pretty certain `igraph` does not do this - I've searched every instance of `cycle` in the full `man` pages, and there is nothing there.

**Comment by mdsumner** [comment]
Very useful, comes up again and again 😋

**Comment by mdsumner** [comment]
@mpadge just checking, did you see [rwalkable from ozunconf2018](https://github.com/ropenscilabs/rwalkable)? 


More formally listed here: http://ozunconf18.ropensci.org/projects/

**Comment by mpadge** [comment]
The [`moveability_to_polygons` function](https://github.com/moveability/moveability/blob/master/R/moveability.R) is now filly implemented courtesy of the [`dodgr_full_cycles()` function](https://atfutures.github.io/dodgr/reference/dodgr_full_cycles.html)
