### ISSUE TITLE
use sc input only; no sf

### ISSUE THREAD

**Issue by mpadge** [moveability/moveability#7]
Ping @mdsumner - we're long overdue for some kind of `sc` chat/plan/scheme. The `sc` routines in `dodgr` are now fully implemented; are considerably faster than `sf` equivalents; and go way beyond what it was possible to do with `sf` (through including elevation effects and the like). This repo is intended to build an engine for a separate project, rather than to be an actual package for anyone to use, and so I'm going to make it exclusively `sc` based. :guitar: rockin!

**Comment by mdsumner** [comment]
Wow, this is so awesome and so radically relevant! I might need to review my career priorities

**Comment by Robinlovelace** [comment]
Join us. In Munster in September for a :beer: if nothing else!

**Comment by mpadge** [comment]
We need to chat Mike, coz I'm in a good spot for what I would hope would be enough input to get SC out there soon. I need it, and people only don't need it via they don't know about it. We gotta do it

**Comment by mdsumner** [comment]
So, last I was working through round-tripping all the classes, it's in better shape now but still needs a few cases fixed. I'm leaning more heavily towards the `0` versions, that include light weight structural indexes for primitives, and always start with a de-duplicated vertex table.  But, you need to re-index for any vertex table modifications. 

I also tried a delta-storage of edges, so a single difference index for each edge pair, with an offset which makes storage competitive. Maybe we should focus on that SC0 type as a standard and build out from that?

**Comment by mpadge** [comment]
Sounds good. I've also learnt lots with latest dodgr, and now store hashes of edge ids as object attributes, to enable identification of need to regenerate tables. I'll have a run through of silicate next week.

**Comment by mpadge** [comment]
That commit covers most of it, but re-opened as prompt to:

- [x] fix `moveability_to_lines` for hard-coded SC-class.
